name: proyek4_nera
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  carousel_slider: ^4.2.1
  curved_navigation_bar: ^1.0.3
  flutter_staggered_grid_view: ^0.6.2
  sliding_up_panel: ^2.0.0+1
  percent_indicator: ^4.0.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/sample_departments.json

