name: proyek4_nera
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  carousel_slider: ^4.2.1
  intl: any
  google_fonts: any
  curved_navigation_bar: ^1.0.3
  flutter_staggered_grid_view: ^0.6.2
  sliding_up_panel: ^2.0.0+1
  percent_indicator: ^4.0.1
  date_picker_timeline: ^1.2.3
  animated_text_kit: ^4.2.2
  top_snackbar_flutter: ^3.0.0+1
  lottie: ^2.3.2
  salomon_bottom_bar: ^3.3.2
  firebase_core: ^2.13.0
  firebase_messaging: 14.6.1
  flutter_launcher_icons: ^0.13.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/Logo_Icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter: 
  assets: 
    - assets/logo/
    - assets/sample_departments.json
    - assets/sample_events.json
    - assets/sample_auth.json
  uses-material-design: true

