// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJEX2yKPeuRv9WWqrtzCZoqVHiWe6iYXI',
    appId: '1:857100388705:web:ff530e3f291275570c9d20',
    messagingSenderId: '857100388705',
    projectId: 'proyek-nera',
    authDomain: 'proyek-nera.firebaseapp.com',
    storageBucket: 'proyek-nera.appspot.com',
    measurementId: 'G-YGJNV7HMR9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGUNlCYePKwrYyoDO067LBoJJl81Hc0-A',
    appId: '1:857100388705:android:a8bc61e956d942bf0c9d20',
    messagingSenderId: '857100388705',
    projectId: 'proyek-nera',
    storageBucket: 'proyek-nera.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjK5m8d1DRWkUOTxdc3t4azDyBq91PMtw',
    appId: '1:857100388705:ios:4749466d37ddab0e0c9d20',
    messagingSenderId: '857100388705',
    projectId: 'proyek-nera',
    storageBucket: 'proyek-nera.appspot.com',
    androidClientId: '857100388705-s7b7qghak3jgu2rf1jo8ullmnpergigo.apps.googleusercontent.com',
    iosClientId: '857100388705-rn1t9ubek9ioi5o6vo35d5c0lm3et8qc.apps.googleusercontent.com',
    iosBundleId: 'com.nera.proyek4Nera',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjK5m8d1DRWkUOTxdc3t4azDyBq91PMtw',
    appId: '1:857100388705:ios:4749466d37ddab0e0c9d20',
    messagingSenderId: '857100388705',
    projectId: 'proyek-nera',
    storageBucket: 'proyek-nera.appspot.com',
    androidClientId: '857100388705-s7b7qghak3jgu2rf1jo8ullmnpergigo.apps.googleusercontent.com',
    iosClientId: '857100388705-rn1t9ubek9ioi5o6vo35d5c0lm3et8qc.apps.googleusercontent.com',
    iosBundleId: 'com.nera.proyek4Nera',
  );
}
